apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ecommerce-kibana
  namespace: logging
spec:
  version: 8.13.4
  count: 1
  elasticsearchRef:
    name: ecommerce-elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1